#!/bin/sh

set -e

echo "Running post-commit hook..."

YELLOW="\033[33m"
GREEN="\033[32m"
RESET="\033[0m"

# Отправляем изменения на основную ветку
echo "${GREEN} [|] Pushing changes to the main branch...${RESET}"
git push origin main

# Отправляем поддерево папки preview/ на ветку preview
echo "${GREEN}[|] Pushing preview/ folder to the preview branch...${RESET}"
git add preview
git add preview
git subtree push --prefix preview origin preview
echo "[+] Preview folder pushed successfully!"

echo "${YELLOW}[+] Post-commit hook completed!${RESET}"
