#!/bin/sh

set -e

echo "Running post-commit hook..."

YELLOW="\033[0;33m"
GREEN="\033[0;32m"
RESET="\033[0m"


# Отправляем поддерево папки preview/ на ветку preview
echo -e "${GREEN}[|] Pushing preview/ folder to the preview branch...${RESET}"
git add -f preview
git subtree push --prefix preview origin preview
echo "[+] Preview folder pushed successfully!"

echo -e "${YELLOW}[+] Post-commit hook completed!${RESET}"
