#!/bin/sh
set -e

echo "${GREEN}Running pre-commit hook...${RESET}"

YELLOW="\033[0;33m"
GREEN="\033[0;32m"
RESET="\033[0m"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

CHANGED_FILES=$(git diff --cached --name-only)

if [ "$CURRENT_BRANCH" = "main" ] && echo "$CHANGED_FILES" | grep -qE '^(apps|test)/'; then
    echo -e "${YELLOW}Changes in 'apps' or 'test' directory detected.${RESET}"

    echo -e "${GREEN}[|] Running formatted and build...${RESET}"
    pnpm format
    pnpm build
    echo "[+] Success formatted and build!"

    echo -e "${GREEN}[|] Remove files to preview...${RESET}"

    rm -f ./preview/vision.bundle.js
    rm -f ./preview/vision.css
    echo "[+] Success remove files to preview!"

    echo -e "${GREEN}[|] Copy files dist/ -> preview/ ...${RESET}"

    cp ./dist/vision.bundle.js ./preview/
    cp ./dist/vision.css ./preview/
    echo "[+] Success copy files!"

    git add .
    echo -e "${GREEN}[+] Send files to branch main -> preview ...${RESET}"
elif echo "$CHANGED_FILES" | grep -qE '^(apps|test)/'; then
    echo -e "${YELLOW}Changes in 'apps|test' directory detected. Only formatting will be done.${RESET}"

    pnpm format
    git add .
    echo -e "${GREEN}[+] Success formatted for apps|test!${RESET}"
else
    echo -e "${YELLOW}No changes in 'apps' directory. Skipping actions.${RESET}"
fi

echo -e "${YELLOW}Husky is successfully!${RESET}"
